### PR TITLE
set style manually when metadata is slow

### LINKED ISSUE #105: Race condition in 2.0.0-beta.7
Hi all, 

I'm seeing a race condition, where if map updates occur while a feature layer is loading, the layer accesses some variables which have not been initialized yet and crashes.

I've [reproduced the problem a gist](https://gist.github.com/PatrickKing/1185c9584cf1e521d8c7). A feature layer is loaded and unloaded at 5 second intervals, and the crash occurs when we call `map.setZoom`.

Not 100% sure this is from esri-leaflet-renderers, but the exception no longer occurs if you comment the line importing renderers in the gist.

Thanks!

Edited to add: For some context, we are using react-leaflet. React has asynchronous event systems which operate in the background, with the result that we encounter this issue reliably in our app. I didn't go hunting for obscure race conditions at random.

### PR DESCRIPTION
**Pull request by jgravois**
resolves #105 

i'm not terribly fond of it, but this fix avoids the race condition and ensures that the appropriate symbology is always utilized by setting styles manually *after* features have already drawn in the rare situation that the metadata response is slower than the initial wave of queries.

* in typical situations, everything should draw perfectly and no errors should appear in the console when loading the repro case the user provided.
* if you add a timeout back into `L.esri.Service.metadata`, you'll see the features draw initially in the default blue, then refresh once the metadata is retrieved.

@kneemer, hope you're well. if you can spare the time to give this PR a quick review, i'd *really* appreciate it.

### CODE REVIEW

File: src/FeatureLayerHook.js [hunk 1]
```diff
@@ -22,19 +21,16 @@ L.esri.FeatureLayer.addInitHook(function () {
...
   }, this);
 
   this.onAdd = function (map) {
     this._loadedMap = map;
-    if (this._metadataLoaded) {
-      oldOnAdd(this._loadedMap);
-      this._addPointLayer(this._loadedMap);
-    }
+    oldOnAdd(this._loadedMap);
+    this._addPointLayer(this._loadedMap);
```
Comment (kneemer) [inline src/FeatureLayerHook.js]: I think we could get rid of `this._loadedMap = map` and just use `map` in the functions.  The variable was used in metadata to see if the map had been loaded but you are using a different variable to achieve the effect.

**Comment by kneemer** [comment]
Hi @jgravois 👋

File: src/FeatureLayerHook.js (hunk 1 above)
Comment (jgravois) [inline src/FeatureLayerHook.js]: agreed!

**Comment by kneemer** [comment]
Not sure why you aren't fond of it.  I think it is actually a better solution to just update the style in the metadata since that is what the metadata is for.  Also, keeping track of which function added the layer always felt a little wrong.

**Comment by jgravois** [comment]
i incorporated your spot on feedback, so i guess we're good to go.
i don't ❤️  the seeing the default symbology flash briefly, but its an edge case, so i can live with it.
